"""RNG snapshot tests per RNG_POLICY.md."""
import json
from pathlib import Path

import pytest

from app.logic.engine import GameEngine
from app.logic.rng import SeededRNG
from app.protocol import SpinMode


FIXTURES_DIR = Path(__file__).parent / "fixtures"


class TestRNGReproducibility:
    """Tests for RNG reproducibility per RNG_POLICY.md."""

    def test_same_seed_produces_same_grid(self):
        """Same seed must produce identical grid."""
        seed = 42

        rng1 = SeededRNG(seed=seed)
        engine1 = GameEngine(rng=rng1)
        result1 = engine1.spin(
            bet_amount=1.00,
            mode=SpinMode.NORMAL,
            hype_mode=False,
            state=None,
        )

        rng2 = SeededRNG(seed=seed)
        engine2 = GameEngine(rng=rng2)
        result2 = engine2.spin(
            bet_amount=1.00,
            mode=SpinMode.NORMAL,
            hype_mode=False,
            state=None,
        )

        assert result1.grid == result2.grid

    def test_same_seed_produces_same_win(self):
        """Same seed must produce identical win."""
        seed = 123

        rng1 = SeededRNG(seed=seed)
        engine1 = GameEngine(rng=rng1)
        result1 = engine1.spin(
            bet_amount=1.00,
            mode=SpinMode.NORMAL,
            hype_mode=False,
            state=None,
        )

        rng2 = SeededRNG(seed=seed)
        engine2 = GameEngine(rng=rng2)
        result2 = engine2.spin(
            bet_amount=1.00,
            mode=SpinMode.NORMAL,
            hype_mode=False,
            state=None,
        )

        assert result1.total_win == result2.total_win
        assert result1.total_win_x == result2.total_win_x

    def test_different_seeds_produce_different_grids(self):
        """Different seeds should produce different grids (with high probability)."""
        rng1 = SeededRNG(seed=1)
        engine1 = GameEngine(rng=rng1)
        result1 = engine1.spin(
            bet_amount=1.00,
            mode=SpinMode.NORMAL,
            hype_mode=False,
            state=None,
        )

        rng2 = SeededRNG(seed=2)
        engine2 = GameEngine(rng=rng2)
        result2 = engine2.spin(
            bet_amount=1.00,
            mode=SpinMode.NORMAL,
            hype_mode=False,
            state=None,
        )

        # Different seeds should produce different grids
        assert result1.grid != result2.grid

    def test_seed_logged_in_seeded_rng(self):
        """SeededRNG must expose seed for logging per RNG_POLICY.md."""
        seed = 999
        rng = SeededRNG(seed=seed)
        assert rng.seed == seed


class TestRNGSnapshots:
    """Snapshot tests for deterministic RNG verification."""

    def test_snapshot_seed_42(self):
        """
        Snapshot test for seed 42.

        This verifies the grid is reproducible and matches the stored snapshot.
        """
        seed = 42
        rng = SeededRNG(seed=seed)
        engine = GameEngine(rng=rng)
        result = engine.spin(
            bet_amount=1.00,
            mode=SpinMode.NORMAL,
            hype_mode=False,
            state=None,
        )

        # Expected grid for seed 42
        # This was generated by running the engine once and recording the output
        # Per RNG_POLICY.md: "Два запуска симуляции с одинаковыми seed и config_hash
        # дают идентичные агрегаты"
        expected_grid = [[6, 0, 4], [3, 7, 7], [9, 2, 5], [0, 3, 5], [0, 3, 6]]

        assert result.grid == expected_grid, (
            f"Grid mismatch for seed {seed}.\n"
            f"Expected: {expected_grid}\n"
            f"Got: {result.grid}"
        )

    def test_snapshot_seed_123(self):
        """Snapshot test for seed 123."""
        seed = 123
        rng = SeededRNG(seed=seed)
        engine = GameEngine(rng=rng)
        result = engine.spin(
            bet_amount=1.00,
            mode=SpinMode.NORMAL,
            hype_mode=False,
            state=None,
        )

        # Expected grid for seed 123
        expected_grid = [[0, 2, 5], [2, 9, 0], [6, 4, 8], [2, 4, 4], [3, 1, 5]]

        assert result.grid == expected_grid, (
            f"Grid mismatch for seed {seed}.\n"
            f"Expected: {expected_grid}\n"
            f"Got: {result.grid}"
        )

    def test_snapshot_seed_999(self):
        """Snapshot test for seed 999."""
        seed = 999
        rng = SeededRNG(seed=seed)
        engine = GameEngine(rng=rng)
        result = engine.spin(
            bet_amount=1.00,
            mode=SpinMode.NORMAL,
            hype_mode=False,
            state=None,
        )

        # Expected grid for seed 999
        expected_grid = [[8, 2, 8], [6, 5, 2], [8, 4, 8], [8, 2, 9], [3, 3, 6]]

        assert result.grid == expected_grid, (
            f"Grid mismatch for seed {seed}.\n"
            f"Expected: {expected_grid}\n"
            f"Got: {result.grid}"
        )


class TestRNGConsecutiveSpins:
    """Tests for consecutive spin reproducibility."""

    def test_consecutive_spins_reproducible(self):
        """Multiple consecutive spins with same seed must be reproducible."""
        seed = 555

        # First run
        rng1 = SeededRNG(seed=seed)
        engine1 = GameEngine(rng=rng1)
        grids1 = []
        for _ in range(5):
            result = engine1.spin(
                bet_amount=1.00,
                mode=SpinMode.NORMAL,
                hype_mode=False,
                state=None,
            )
            grids1.append(result.grid)

        # Second run with same seed
        rng2 = SeededRNG(seed=seed)
        engine2 = GameEngine(rng=rng2)
        grids2 = []
        for _ in range(5):
            result = engine2.spin(
                bet_amount=1.00,
                mode=SpinMode.NORMAL,
                hype_mode=False,
                state=None,
            )
            grids2.append(result.grid)

        # All grids must match
        assert grids1 == grids2
